# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: blog@reimondo
email: reimondo.zero#gmail.com
description: > # this means to ignore newlines until "baseurl:"
    Prefer some dark arts.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog.reimondo.org" # the base hostname & protocol for your site
twitter_username: ccreimondo
github_username: ccreimondo

# Build settings
markdown: kramdown

timezone: Asia/Chongqing
